### ISSUE TITLE
Deprecated voku in php8.4alpha1

### ISSUE THREAD

**Issue by zxstudio-llc** [voku/portable-ascii#101]
Deprecated: voku\helper\ASCII::to_ascii(): Implicitly marking parameter $replace_single_chars_only as nullable is deprecated, the explicit nullable type must be used instead in /Users/zx-studio/Herd/zx-studioweb/vendor/voku/portable-ascii/src/voku/helper/ASCII.php on line 795

**Comment by crynobone** [comment]
Hi @voku , PR https://github.com/voku/portable-ascii/pull/102 should solve the deprecation. Any chance we can merge that and get a tag soon?

**Comment by Diddyy** [comment]
@voku Hey! Whats stopping this from being merged? Is there anything anyone can do to help progress it? :)

**Comment by zxstudio-llc** [comment]
Yesterday I tried version 8.4 again but the error still appears so I continue working with version 8.3

**Comment by crynobone** [comment]
@voku PHP 8.4.0 is planned for November 21st, 2024 (in 10 days), can we get a this solve ASAP?

**Comment by MGeurts** [comment]
PHP 8.4.0 and even 8.4.1 are already published at [https://windows.php.net/downloads/releases/](https://windows.php.net/downloads/releases/).

Could this please be resolved?
The warning is showing up in all Laravel 11 applications on PHP 8.4.

Thanks.

**Comment by crynobone** [comment]
@duncanmcclean Unfortunately, after some time, it isn't working 100%, and we still need to wait for a fix for this project.

**Comment by duncanmcclean** [comment]
Looks like this might have been addressed by #105?

**Comment by phildawson-gravity** [comment]
So the current Laravel framework has been bumped to portable-ascii ^2.0.2 in 11.33

"voku/portable-ascii": "^2.0.2"

Edit: Just realised Duncan already mentioned that.

**Comment by voku** [comment]
Version 2.1.0

- run all checks and tests up to PHP 8.5
- raise the minimum PHP version from 7.0 to 7.1
